services:
  selenium-hub:
    image: ${IMAGE_NAME:-selenium/hub}:${IMAGE_TAG:-latest}
    hostname: ${SE_HUB_HOST}
    environment:
      SE_HUB_HOST:
      SE_HUB_PORT:
      SE_SESSION_REQUEST_TIMEOUT:
      SE_SESSION_RETRY_INTERVAL:
      SE_OPTS:
      JAVA_OPTS:
    networks:
      selenium-net:
      gitlab-net:
      traefik-net:
    healthcheck:
      test: curl -sSL http://localhost:${SE_HUB_PORT}/wd/hub/status
      interval: ${HEALTHCHECK_INTERVAL:-30s}
      timeout: ${HEALTHCHECK_TIMEOUT:-15s}
      retries: ${HEALTHCHECK_RETRIES:-5}
      start_period: ${HEALTHCHECK_START_PERIOD:-1m}
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        delay: ${RESTART_DELAY:-5s}
      update_config:
        delay: ${UPDATE_DELAY:-1m}
      labels:
        traefik.enable: ${TRAEFIK_ENABLE:-true}
        traefik.http.routers.selenium-hub.entrypoints: ${TRAEFIK_ENTRYPOINT:-http}
        traefik.http.routers.selenium-hub.rule: Host(`${TRAEFIK_SUBDOMAIN:-selenium}.${PUBLIC_HOSTNAME}`)
        traefik.http.middlewares.selenium-hub-auth.basicauth.users: ${TRAEFIK_AUTH}
        traefik.http.routers.selenium-hub.middlewares: selenium-hub-auth
        traefik.http.services.selenium-hub.loadbalancer.server.port: ${SE_HUB_PORT}
      resources:
        limits:
          cpus: '${RESOURCES_LIMITS_CPUS:-0.5}'
          memory: ${RESOURCES_LIMITS_MEMORY:-1G}
        reservations:
          cpus: '${RESOURCES_RESERVATIONS_CPUS:-0.001}'
          memory: ${RESOURCES_RESERVATIONS_MEMORY:-256M}

networks:
  selenium-net:
    name: ${SELENIUM_NET_NAME:-selenium-net}
    driver: ${SELENIUM_NET_DRIVER:-overlay}
    attachable: ${SELENIUM_NET_ATTACHABLE:-true}

  gitlab-net:
    name: ${GITLAB_NET_NAME:-gitlab-net}
    driver: ${GITLAB_NET_DRIVER:-overlay}
    external: true

  traefik-net:
    name: ${TRAEFIK_NET_NAME:-traefik-net}
    driver: ${TRAEFIK_NET_DRIVER:-overlay}
    external: true
